name: foodhub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/backgrounds/
  fonts:
    - family: Phosphate
      fonts:
        - asset: assets/fonts/PhosphateInline.ttf
    - family: Sofia pro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular.otf
        - asset: assets/fonts/Sofia-Pro-Bold.otf
        - asset: assets/fonts/Sofia-Pro-Medium.otf
        - asset: assets/fonts/Sofia-Pro-Semi-Bold.otf


